### ISSUE TITLE
Get supported approver e-mails when using email as validation method

### ISSUE THREAD

**Issue by Jaykju** [psw-group/api-v1#15]
In the previous API it was possible to get the supported approver e-mail addresses before submitting an order.  
In this version this feature seems to be missing.

All the examples just use `webmaster@ssl-test.de` so I am guessing that this is a viable default. 
I remember the available options to be different based on the selected product or ca. 

Are there plans to bring this back or are there other guidelines on what restricts the allowed e-mail addresses that would allow me to curate a list of options?

**Comment by binsoul** [comment]
You are right that some CAs supported validation emails for subdomains some time ago. But most stopped supporting it. So we didn't implement an endpoint for it, because the list of possible email addresses is quite static now. All CAs support the following email adresses:

- admin@domain
- administrator@domain
- hostmaster@domain
- postmaster@domain
- webmaster@domain

Domain has to be the top-level domain, e.g. "ssl-test.de" for a certificate with the common name "level2.level1.ssl-test.de".

**Comment by Jaykju** [comment]
Thank you for clarifying
