### ISSUE TITLE
Bug: Inconsistency in #Job definition

### ISSUE THREAD

**Issue by dmke** [psw-group/api-v1#5]
The `#Job/state` is declared to be an integer, but as example value "submitted" is given.

![image](https://user-images.githubusercontent.com/327411/85535341-5f22bc80-b612-11ea-8442-6bef04e1ace4.png)

![image](https://user-images.githubusercontent.com/327411/85538277-056fc180-b615-11ea-85bf-bc097d4db7cb.png)

Obviously, it is kind of an enum (there is only a finite set of possible states), but is not clear what the concrete values are. For `#Order/state` we have an `/v1/order-states` endpoint, but nothing equivalent for jobs.

**Comment by binsoul** [comment]
The state of the job is now declared as string including the possible values "submitted", "running", "succeeded" and "failed".

![grafik](https://user-images.githubusercontent.com/14879936/85690031-737abe00-b6d3-11ea-8a62-28503ed5b3a1.png)

Because there will never be other states I think we don't need an additional endpoint for it. An enum should be enough.

**Comment by dmke** [comment]
Thanks!
